# Grafana가 뜰 때 Prometheus 데이터소스를 자동으로 등록한다.
apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
