CREATE TABLE festival_accuracy_vote (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    festival_id BIGINT                                  NOT NULL,
    member_id   UUID                                    NOT NULL,
    vote_type   VARCHAR(16)                             NOT NULL,
    created_at  TIMESTAMP(6)                            NOT NULL,
    updated_at  TIMESTAMP(6)                            NOT NULL,

CONSTRAINT pk_festival_accuracy_vote
      PRIMARY KEY (id),

CONSTRAINT uk_festival_accuracy_vote_festival_member
      UNIQUE (festival_id, member_id)
);
