CREATE TABLE member (
    id          UUID         NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(32)  NOT NULL,
    nickname    VARCHAR(255) NOT NULL,
    profile_img VARCHAR(2048),
    phone       VARCHAR(255),
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6),
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uk_member_email ON member (email) WHERE deleted_at IS NULL;

CREATE TABLE public_festival_source (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source JSONB                                   NOT NULL,
    CONSTRAINT pk_public_festival_source PRIMARY KEY (id)
);

CREATE TABLE festival (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id         UUID,
    provider_type     VARCHAR(32)                             NOT NULL,
    inst_nm           VARCHAR(255),
    title             VARCHAR(255),
    category          VARCHAR(255),
    manager           VARCHAR(255),
    content           JSONB,
    url               VARCHAR(2048),
    img_url           VARCHAR(2048),
    begin_de          TIMESTAMP(6)                            NOT NULL,
    end_de            TIMESTAMP(6)                            NOT NULL,
    event_tm_info     VARCHAR(255)                            NOT NULL,
    partcpt_expn_info VARCHAR(255),
    telno_info        VARCHAR(255),
    host_inst_nm      VARCHAR(255),
    hmpg_url          VARCHAR(2048),
    writng_de         TIMESTAMP(6),
    status            VARCHAR(32),
    CONSTRAINT pk_festival PRIMARY KEY (id)
);

CREATE TABLE post (
    id         UUID         NOT NULL,
    member_id  UUID         NOT NULL,
    pu_fev_id  BIGINT,
    title      VARCHAR(255) NOT NULL,
    content    JSONB        NOT NULL,
    thumbnail  VARCHAR(2048),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE "comment" (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id    UUID                                    NOT NULL,
    member_id  UUID                                    NOT NULL,
    content    TEXT                                    NOT NULL,
    created_at TIMESTAMP(6)                            NOT NULL,
    updated_at TIMESTAMP(6)                            NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE "like" (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    src_id    UUID                                    NOT NULL,
    member_id UUID                                    NOT NULL,
    "like"    BIGINT                                  NOT NULL,
    CONSTRAINT pk_like PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uk_like_src_member ON "like" (src_id, member_id);

CREATE TABLE inquiry (
    id        UUID         NOT NULL,
    member_id UUID,
    title     VARCHAR(255) NOT NULL,
    content   TEXT         NOT NULL,
    img       VARCHAR(2048),
    answer    TEXT,
    status    VARCHAR(32),
    CONSTRAINT pk_inquiry PRIMARY KEY (id)
);

CREATE TABLE refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id  UUID                                    NOT NULL,
    token_hash VARCHAR(255)                            NOT NULL,
    expires_at TIMESTAMP(6)                            NOT NULL,
    created_at TIMESTAMP(6)                            NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);
