-- 행사 후기와 분리된 자유 커뮤니티 게시글과 댓글을 저장한다.
CREATE TABLE community_post (
    id          UUID         NOT NULL,
    member_id   UUID         NOT NULL,
    category    VARCHAR(32)  NOT NULL,
    title       VARCHAR(100) NOT NULL,
    content     TEXT         NOT NULL,
    view_count  BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6),
    CONSTRAINT pk_community_post PRIMARY KEY (id),
    CONSTRAINT fk_community_post_member FOREIGN KEY (member_id) REFERENCES member (id)
);

CREATE INDEX idx_community_post_category_created_at
    ON community_post (category, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE community_comment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id     UUID         NOT NULL,
    member_id   UUID         NOT NULL,
    content     VARCHAR(500) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6),
    CONSTRAINT pk_community_comment PRIMARY KEY (id),
    CONSTRAINT fk_community_comment_post FOREIGN KEY (post_id) REFERENCES community_post (id),
    CONSTRAINT fk_community_comment_member FOREIGN KEY (member_id) REFERENCES member (id)
);

CREATE INDEX idx_community_comment_post_created_at
    ON community_comment (post_id, created_at)
    WHERE deleted_at IS NULL;
